apiVersion: v1
kind: Secret
metadata:
  name: database-endpoint
type: Opaque
stringData:
  primary_endpoint: "YUGABYTEDB_PRIMARY_HOST"
  port: "5433"
  user: "YUGABYTEDB_USERNAME"
  password: "YUGABYTEDB_PASSWORD"
  # Uncomment if you'd like to provide additional connection endpoints
  # additional_endpoints: "YUGABYTEDB_ADDITIONAL_ENDPOINTS"
