image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080 # Application frontend
    onOpen: open-browser
  - port: 7001 # YugabyteDB UI console
    onOpen: notify
  - port: 9005 # Minio console
    onOpen: notify
  - port: 8761 # Discovery Server UI
    onOpen: notify

  # Disable notifications about the following ports
  - port: 5433
    onOpen: ignore
  - port: 9042
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9001
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 12000
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 8888
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - name: YugabyteDB Cluster
    command: |
      yugabyted start --base_dir=$YB_STORE/node1 --listen=127.0.0.1 --master_webserver_port=$YB_WEB_PORT --tserver_webserver_port=$TSERVER_WEB_PORT
      yugabyted start --base_dir=$YB_STORE/node2 --listen=127.0.0.2 --join=127.0.0.1  --master_webserver_port=$YB_WEB_PORT --tserver_webserver_port=$TSERVER_WEB_PORT
      yugabyted start --base_dir=$YB_STORE/node3 --listen=127.0.0.3 --join=127.0.0.3  --master_webserver_port=$YB_WEB_PORT --tserver_webserver_port=$TSERVER_WEB_PORT

  # There is a file-system related issue that prevents starting Minio server within the Gitpod workspace
  # - name: Minio
  #   command: minio server $MINIO_STORE --console-address :$MINIO_CONSOLE_PORT

  - name: Config Server
    init: | 
      cd config-server
      mvn clean package
    command: mvn spring-boot:run

  - name: Discovery Server
    init: | 
      cd discovery-server
      mvn clean package
    command: mvn spring-boot:run  
  
  - name: Attachments Microservice
    init: | 
      cd attachments
      mvn clean package
    command: |
      gp ports await 8888 && gp preview $(gp url 8888)/messenger/dev
      gp ports await 8761 && gp preview $(gp url 8761)
      mvn spring-boot:run

  - name: Messenger Microservice
    init: | 
      cd messenger
      mvn clean package
    command: |
      gp ports await 8888 && gp preview $(gp url 8888)/messenger/dev
      gp ports await 8761 && gp preview $(gp url 8761)
      gp ports await 5433
      mvn spring-boot:run