version: '3.9'
services:
  config-server:
    image: config-server:latest
    build: ./config-server

  discovery-server:
    image: discovery-server:latest
    build: ./discovery-server
    ports:
      - "8761:8761"

  minio:
    image: quay.io/minio/minio:RELEASE.2022-08-26T19-53-15Z
    volumes:
      - minio_data:/data
    ports:
      - "9005:9005"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9005"

  yb-master-0:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-master-0
    hostname: yb-master-0.zone.region.cloud
    command: bash -c "rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-master --fs_data_dirs=/home/yugabyte/data --placement_cloud=cloud --placement_region=region --placement_zone=zone --rpc_bind_addresses=yb-master-0.zone.region.cloud:7100 --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --replication_factor=3 --rpc_connection_timeout_ms=15000"
    ports:
      - "7001:7000"

  yb-tserver-0:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-tserver-0
    hostname: yb-tserver-0.zone.region.cloud
    command: bash -c " rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-tserver --placement_cloud=cloud --placement_region=region --placement_zone=zone --enable_ysql=true --fs_data_dirs=/home/yugabyte/data --rpc_bind_addresses=yb-tserver-0.zone.region.cloud:9100 --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --ysql_num_shards_per_tserver=2 --rpc_connection_timeout_ms=15000"
    ports:
      - "9001:9000"
      - "5433:5433"
    depends_on:
      - yb-master-2

  yb-master-1:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-master-1
    hostname: yb-master-1.zone.region.cloud
    command: bash -c " rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-master --fs_data_dirs=/home/yugabyte/data --placement_cloud=cloud --placement_region=region --placement_zone=zone --rpc_bind_addresses=yb-master-1.zone.region.cloud:7100 --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --replication_factor=3 --rpc_connection_timeout_ms=15000"
    ports:
      - "7002:7000"
    depends_on:
      - yb-master-0

  yb-tserver-1:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-tserver-1
    hostname: yb-tserver-1.zone.region.cloud
    command: bash -c " rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-tserver --placement_cloud=cloud --placement_region=region --placement_zone=zone --enable_ysql=true --fs_data_dirs=/home/yugabyte/data --rpc_bind_addresses=yb-tserver-1.zone.region.cloud:9100 --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --ysql_num_shards_per_tserver=2 --rpc_connection_timeout_ms=15000"
    ports:
      - "9002:9000"
      - "5434:5433"
    depends_on:
      - yb-master-2

  yb-master-2:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-master-2
    hostname: yb-master-2.zone.region.cloud
    command: bash -c " rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-master --fs_data_dirs=/home/yugabyte/data --placement_cloud=cloud --placement_region=region --placement_zone=zone --rpc_bind_addresses=yb-master-2.zone.region.cloud:7100 --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --replication_factor=3 --rpc_connection_timeout_ms=15000"
    ports:
      - "7003:7000"
    depends_on:
      - yb-master-1

  yb-tserver-2:
    image: yugabytedb/yugabyte:2.15.3.0-b231
    container_name: yb-tserver-2
    hostname: yb-tserver-2.zone.region.cloud
    command: bash -c " rm -rf /tmp/.yb* ; /home/yugabyte/bin/yb-tserver --placement_cloud=cloud --placement_region=region --placement_zone=zone --enable_ysql=true --fs_data_dirs=/home/yugabyte/data --rpc_bind_addresses=yb-tserver-2.zone.region.cloud:9100 --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 --ysql_num_shards_per_tserver=2 --rpc_connection_timeout_ms=15000"
    ports:
      - "9003:9000"
      - "5435:5433"
    depends_on:
      - yb-master-2

  attachments:
    image: attachments:latest
    build: ./attachments
    depends_on:
      - config-server
      - discovery-server
      - minio
    environment:
      - CONFIG_SERVER_HOST=config-server
      - CONFIG_SERVER_PORT=8888
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - MINIO_HOST=minio
      - MINIO_PORT=9000

  messenger:
    image: messenger:latest
    build: ./messenger
    depends_on:
      - config-server
      - discovery-server
      - yb-tserver-1
      - yb-master-1
    environment:
      - CONFIG_SERVER_HOST=config-server
      - CONFIG_SERVER_PORT=8888
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - DB_PRIMARY_ENDPOINT=yb-tserver-1.zone.region.cloud
      - DB_PORT=5433
      - DB_DATASOURCE_NAME=com.yugabyte.ysql.YBClusterAwareDataSource
      - DB_ADDITIONAL_ENDPOINTS=yb-tserver-2.zone.region.cloud:5433,yb-tserver-3.zone.region.cloud:5433
    ports:
      - "8080:8080"

volumes:
  minio_data:
