apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: geo-messenger
  labels:
    app: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
